id: A97B48DB5
base_file: f5A0F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:02:07.318365
  last_modified_at: 2022-06-05 20:02:07.318372
